name: Build and Push Docker Image

on:
  schedule:
    # Schedule the workflow to run at 1:25am UTC on every Monday
    - cron: '25 1 * * 1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub using a token
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker Image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/kali-sshd"
        DATE_TAG=$(date +'%Y.%V')
        echo "Building image: $IMAGE_NAME"
        docker build -t "${IMAGE_NAME}:${DATE_TAG}" -t "${IMAGE_NAME}:latest" .
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
        echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_ENV

    # Step 4: Push the Docker image to the registry
    - name: Push Docker Image
      run: |
        docker push "${IMAGE_NAME}:${DATE_TAG}"
        docker push "${IMAGE_NAME}:latest"

